### ISSUE TITLE
EnvironmentError when installing library if sunbeam has not been added to path

### ISSUE THREAD

**Issue by Lswhiteh** [sunbeam-labs/sunbeam#175] opened 2018-11-27 19:11 UTC
Pardon my ignorance if this is already known, but after doing a re-install of sunbeam I kept running into the error "Could not install packages due to an EnvironmentError:" with "Errno13 Permission denied" errors while installing the library from the install.sh script. 

After some troubleshooting, I found that after adding the sunbeam installation to PATH cleared that up. Not sure if this is a conda problem or an issue with pip and temp directories (I've had similar issues before with pip not playing nice). I was wondering if this is reproducible for people on other machines, and if so, should it be noted in the docs? I have been able to repeat the issue on separate machines where I have the same level of access by simply downloading and running the install script without any alterations.

For reference I'm installing and running sunbeam on an HPC and do not have sudo access.

**Comment by eclarke** [comment] 2018-11-27 19:32
I haven't heard of this issue before, thanks for reporting it. Is there a way you could post the full stack trace from the install script?

**Comment by louiejtaylor** [comment] 2018-11-27 19:35
Thanks for the issue! I actually haven't run into this problem before, on either our lab server or HPC. The only thing I've ever needed to add to my PATH is the conda dir. A few questions that may be useful in localizing the problem (and maybe @eclarke will have further insight):

 1. Is the conda/miniconda directory in the standard location (e.g. /home/lswhiteh)?
 2. Is your install a fresh install, or are you updating an existing install?
 3. Are you working from the [Quick Start Guide](https://sunbeam.readthedocs.io/en/latest/quickstart.html) and installing the stable branch, or are you grabbing the dev branch (which I think is the default that gets `git clone`'d)?

Maybe the answer to Question 2 plus some more error traceback context (i.e. where in the install it failed) can help track it down. Thanks again!

**Comment by Lswhiteh** [comment] 2018-11-27 19:44
1. Conda is installed in the shared software directory `/N/soft/rhel7/anaconda/python3.6/4.3.1/bin/conda` but environments are stored in user dirs `/N/u/lswhiteh/Carbonate/.conda/envs/sunbeam`
Here's the system I'm running it on, if that helps https://kb.iu.edu/d/aolp

2. I ran into the issue with fresh installs, I have yet to try replicating it with existing installs but I have a feeling that with the path already being fixed it won't be an issue. I will attempt this when I get a chance.

3. I was working from the quickstart guide using the stable branch. 

Here's the exact error I was getting: `Could not install packages due to an EnvironmentError: [('/N/dc2/scratch/lswhiteh/sunbeam-stable/.git/objects/pack/pack-826ac03471d3bed8a87e3b71838076d1bcd4361f.pack', '/tmp/846281.s1/pip-req-build-m5iqfcxt/.git/objects/pack/pack-826ac03471d3bed8a87e3b71838076d1bcd4361f.pack', "[Errno 13] Permission denied: '/tmp/846281.s1/pip-req-build-m5iqfcxt/.git/objects/pack/pack-826ac03471d3bed8a87e3b71838076d1bcd4361f.pack'"), ('/N/dc2/scratch/lswhiteh/sunbeam-stable/.git/objects/pack/pack-826ac03471d3bed8a87e3b71838076d1bcd4361f.idx', '/tmp/846281.s1/pip-req-build-m5iqfcxt/.git/objects/pack/pack-826ac03471d3bed8a87e3b71838076d1bcd4361f.idx', "[Errno 13] Permission denied: '/tmp/846281.s1/pip-req-build-m5iqfcxt/.git/objects/pack/pack-826ac03471d3bed8a87e3b71838076d1bcd4361f.idx'")]
`

Here's the debug output https://gist.github.com/Lswhiteh/0f6551c1e7436479a6295b520188ec8f

**Comment by eclarke** [comment] 2018-11-27 20:15
This is different from our HPC setup so I'm not sure I'll be able to reproduce, but it looks to me like the error you're reporting and the one in the debug log are different. For the one in the comment above, it suggests that you're not able to write to that `/tmp` directory (correct me if I'm wrong). If that's the case, you could try specifying a different $TMPDIR before running the command, maybe a folder you create in your directory like so:
```sh
mkdir ~/tmp
TMPDIR=$HOME/tmp ./install.sh
```
-----

The reason the install script is failing in your debug output seems to be the fact that `/N/u/lswhiteh/Carbonate/.local/bin` isn't in your $PATH. I am not clear why pip is trying to install the scripts there, rather than in the conda env, but when it checks after library install that it can execute those scripts, it fails because it didn't install them to a directory in your path. (c.f. https://gist.github.com/Lswhiteh/0f6551c1e7436479a6295b520188ec8f#file-sunbeamlibraryerror-txt-L10) What folder exactly do you add to your PATH to make this work? Is it that one?

(Finally, I'm noticing that the script is already finding a Conda environment named sunbeam. I don't think that's the issue, but you may want to try a fresh environment using `conda env remove sunbeam` and try again.)

**Comment by Lswhiteh** [comment] 2018-11-27 20:20
Thank you for the tips, I'll keep that in mind. Not sure why pip is doing that either, and it's not consistent across packages so I can't narrow down why. 

Yes, I added the `/N/u/lswhiteh/Carbonate/.local/bin` to PATH, which I thought was there before but apparently that was changed when I was changing some settings.

Yes I was aware of the already existing env, that was on another attempt to just install the library after having a fresh env installed since trying to install them both at the same time didn't work. 

Sorry this seems to be just a myself error with pip, probably didn't deserve an issue but I appreciate the help!

**Comment by Lswhiteh** [comment] 2018-11-27 20:50
Not sure if I'm missing something, but after a search both on my local install.sh and the repo there aren't any instances of `pip install --user`, only `pip install --upgrade`. I've reset my path and am attempting it again, will update this when it finishes.

**Comment by eclarke** [comment] 2018-11-27 20:53
You're right, it's not on the repo! Weird. I was referencing your posted debug log, which does have 'pip install --user' in it. I'm not sure where that came from then...

**Comment by Lswhiteh** [comment] 2018-11-27 20:54
Could've been me fiddling with it after a few failed attempts with the stock version, now that I think about it.

**Comment by eclarke** [comment] 2018-11-27 21:00
The install should be using conda's version of pip, which works relative to conda's version of python. But even conda's version of pip may reach out into the /tmp folder, and if there are issues writing to /tmp, it could trigger the permissions error. Have you tried the `TMPDIR=~/tmp` suggestion?

**Comment by Lswhiteh** [comment] 2018-11-27 21:58
No such luck when using tmpdir, it doesn't seem to stick. Am I doing something incorrect with setting up the tmpdir? https://gist.github.com/Lswhiteh/f1a5718fdbf6557d09a1afbf01bfda85

**Comment by eclarke** [comment] 2018-11-28 20:04
Hmm. You're doing everything right, and it did change tmpdir. But I'm now noticing that the permissions error seems to be centered around the `sbx_report` extension. Does that exist in your sunbeam-stable directory, and if so, can you remove it and try again? Alternatively, could you clone sunbeam-stable to a brand new directory like `sunbeam-stable2` for instance and install from there?

If there's an issue upgrading sunbeam when we have extensions installed, that's a good thing to know and something we need to fix.

**Comment by Lswhiteh** [comment] 2018-11-28 21:01
I'm currently installing sunbeam-stable in 3 scenarios, all in clean directories and new environments without altering anything from base:
1. Without any extensions downloaded or installed
2. With sbx_report downloaded into the extensions folder but not installed
3. With an environment made, sbx_report installed before sunbeam
(If #3 fails I will try to install it on a premade environment but without the sbx_report installation)

I will update this with an edit after they finish installing, but it might take a bit.

**Comment by ressy** [comment] 2018-12-03 18:34
This is a long shot, but are we completely certain the pip that's getting executed really is conda's pip?  It's included with Anaconda/Miniconda at install-time, but Sunbeam doesn't explicitly demand pip as a conda package, and I can see that it's possible to end up in that state if conda's pip isn't there for whatever reason.  (I just tested that with `conda remove pip` in an older install of Miniconda, and it let me do it, but on a newer one I see that conda actually tries to prevent you from removing it.)

@Lswhiteh, what do these give you?

```
which -a pip
pip --version
```

(Apologies if any of that info was already in the log text and I've missed it.)

**Comment by eclarke** [comment] 2018-12-03 18:35
Good thought, and I’d add to specifically try those commands within the sunbeam conda env.

**Comment by ressy** [comment] 2018-12-13 15:04
Another idea for this: I made a wrapper script and Makefile to go through the installation and testing steps in an isolated directory, with a fresh Anaconda, condarc configuration, etc:

https://github.com/ressy/sunbeam-install-debug

I set the Anaconda version to default to the same that looks to be installed in your shared software directory and tested this on our cluster running CentOS 7, so this should hopefully be similar to your setup.  If that works for you (just clone it and run `make` in that directory), we can try to compare that side-by-side with the usual install and see what's causing the trouble.

**Comment by ressy** [comment] 2019-03-12 13:44
@Lswhiteh I'm going through some of the open issues and realized we still hadn't figured this one out.  Are you still having trouble?

**Comment by Lswhiteh** [comment] 2019-03-12 14:08
Apologies, I got busy finishing up semester projects and had stopped using sunbeam once the project was completed. As this issue only seems to affect me, I believe that it was an issue with the way our modules are handled on the HPC at IU, I did not have an issue when installed locally.

**Comment by ressy** [comment] 2019-03-12 14:28
No worries!  If you're done with it for the time being, I'll close this issue for now, but we can re-open at any point down the road if you want to give it another try on your HPC environment.

**Comment by YiweiNiu** [comment] 2019-07-01 06:54
Hi,

I got this similar error when trying to install sunbeam.

```shell
ERROR: Could not install packages due to an EnvironmentError: [('/home/niuyw/software/sunbeam-stable/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.idx', '/tmp/pip-req-build-n_e7sf9w/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.idx', "[Errno 13] Permission denied: '/tmp/pip-req-build-n_e7sf9w/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.idx'"), ('/home/niuyw/software/sunbeam-stable/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.pack', '/tmp/pip-req-build-n_e7sf9w/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.pack', "[Errno 13] Permission denied: '/tmp/pip-req-build-n_e7sf9w/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.pack'")]
```

The `pip` is from the `sunbeam` conda environment (when activating `sunbeam` env) and the version is the latest.

```shell
(sunbeam) niuyw@admin:~/software/sunbeam-stable$ which pip
~/software/anaconda3/envs/sunbeam/bin/pip
(sunbeam) niuyw@admin:~/software/sunbeam-stable$ pip --version
pip 19.1.1 from /home/niuyw/software/anaconda3/envs/sunbeam/lib/python3.6/site-packages/pip (python 3.6)
```

Here is the debug infor: [debug.txt](https://github.com/sunbeam-labs/sunbeam/files/3344218/debug.txt)

I tried the solutions mentioned above, but could not solve this problem.

Bests,
Yiwei Niu

**Comment by ressy** [comment] 2019-07-08 17:10
@YiweiNiu you're right, this looks like the same problem Lswhiteh was having.  Thanks for providing that info.  What kind of environment are you working in?  (Is it also a TORQUE cluster on a Red Hat-like distribution like for Lswhiteh for example?)  Could you try git cloning this repo to your home directory, cd'ing into it, and running `make`?  https://github.com/ressy/sunbeam-install-debug

Doing some more searching just now I wonder if we're running into this old pip issue and possibly this exact instance of it: https://github.com/pypa/pip/issues/4525#issuecomment-495305878.  It talks about issues with extended attributes on network filesystems, which wouldn't make much sense for /tmp, but *would* for home directories that are the source for the shutil functions pip uses.  But if we can get things working with a self-contained install for troubleshooting purposes we can compare to the failing case and try to narrow that down.

**Comment by YiweiNiu** [comment] 2019-07-10 06:36
Sorry for the delayed reply.

> What kind of environment are you working in? (Is it also a TORQUE cluster on a Red Hat-like distribution like for Lswhiteh for example?)

Yes, I am working on a TORQUE cluster, and each node has a CentOS 6 system. I could list more information about our system if it helps.

> Could you try git cloning this repo to your home directory, cd'ing into it, and running `make`?

I ran this and ended up with the same 'permission' error. Here is the full debugging log: [sunbeam-install-debug.log.txt](https://github.com/sunbeam-labs/sunbeam/files/3375983/sunbeam-install-debug.log.txt).

Since the pip I used was the latest, so, it should not be a bug of pip, I guess?

Thank you for helping me.

Bests,
Yiwei Niu

**Comment by ressy** [comment] 2019-07-10 14:27
Not pip but possibly shutil, if it's the bug I'm wondering about.  That only got [fixed back in May](https://github.com/python/cpython/commit/79efbb719383386051c72f2ee932eeca8e033e6b#diff-69f781dfa4a6697ad701fd742bc0d81e) and it's part of Python so most of us are probably still using an earlier version.  I think this looks like a plausible culprit since the files the error message complains about are exactly those I find that have u-w permissions in the local copy of the repository.  Adding some whitespace to the error to make the file paths more readable:

```
ERROR: Could not install packages due to an EnvironmentError:

[

(
'/home/niuyw/software/sunbeam-stable/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.idx',
'/tmp/pip-req-build-n_e7sf9w/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.idx',
"[Errno 13] Permission denied: '/tmp/pip-req-build-n_e7sf9w/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.idx'"),

('/home/niuyw/software/sunbeam-stable/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.pack',
'/tmp/pip-req-build-n_e7sf9w/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.pack',
"[Errno 13] Permission denied: '/tmp/pip-req-build-n_e7sf9w/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.pack'")

]
```
Looking for files not writable by the user:

```
$ find sunbeam/ ! -perm -200 -ls
10924311249   1236 -r--r--r--   1 jesse    jesse     1263682 Jul 10 10:11 sunbeam/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.pack
10924311250     76 -r--r--r--   1 jesse    jesse       75048 Jul 10 10:11 sunbeam/.git/objects/pack/pack-8eb61487f10ba02abe9863e47dabb918db4b12de.idx
```

This is a bit of a guess, but what happens if you try this command before running the install step? `chmod u+w sunbeam/.git/objects/pack/*`  Does the installation work then?  (If not, what output do you get from `df -hT`?  If you clone and try to sunbeam-install-debug repo in /tmp does it work?)

**Comment by YiweiNiu** [comment] 2019-07-11 05:10
Hi ressy,

You are right. `sunbeam` could be installed successfully by using both methods (cloning into in `/tmp` and `chmod` way).

Here are the installation log of  `/tmp` way [install.debugging.in_tmp.txt](https://github.com/sunbeam-labs/sunbeam/files/3380328/install.debugging.in_tmp.txt) and `chmod` way [install.debugging.after_chmod.txt](https://github.com/sunbeam-labs/sunbeam/files/3380331/install.debugging.after_chmod.txt). In case they are still useful.

Thank you for all your help. I can try `sunbeam` now. It looks cool.

Bests,
Yiwei Niu

**Comment by ressy** [comment] 2019-07-12 15:27
Great, glad you hear it!  @Lswhiteh I expect this might solve your old issue too, so if you do end up trying it again on your Carbonate cluster give that chmod command a try before running the install.

We could try to address this in the install script, but on the other hand it's an edge case for filesystems with extended attributes and should also become moot as the latest Python 3 version eventually makes its way into our defaults during installation.  So I'm going to declare this a viable workaround for the time being and re-close the issue.  Thanks for your help debugging Yiwei.

**Closed by ressy** 2019-07-12 15:27 UTC
