### ISSUE TITLE
Problem running Sunbeam

### ISSUE THREAD

**Issue by telatin** [sunbeam-labs/sunbeam#272] opened 2020-02-20 11:49 UTC
Hello,
I just tried running Sunbeam.

I installed it via:
```
git clone -b stable https://github.com/sunbeam-labs/sunbeam sunbeam-stable` and the ./install.sh
tests/run_tests.bash -e sunbeam
```
The tests ran smoothly.

I have a directory with raw reads in the format `samplename_R{1,2}.fq.gz`, so I prepared the sample sheet with:
`sunbeam init sunbeam_test --data_fp $PWD/reads --format {sample}_R{rp}.fq.gz`

When running with:
`sunbeam run  --configfile sunbeam_test/sunbeam_config.yml`

It fails at the very beginning but I don't understand the problem:
```
[Thu Feb 20 11:43:11 2020]
rule sample_intake:
    input: /home/ubuntu/informatics/GMH/projects/sc_ap/reads2/AP66_R2.fastq.gz
    output: /home/ubuntu/informatics/GMH/projects/sunbeam_test/sunbeam_output/qc/00_samples/AP66_2.fastq.gz
    jobid: 61
    wildcards: sample=AP66, rp=2

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ubuntu/informatics/GMH/projects/.snakemake/log/2020-02-20T114303.321764.snakemake.log
```

**Comment by louiejtaylor** [comment] 2020-02-20 14:09
Hi @telatin, thanks for the issue! The `sample_intake` rule is the first rule run by the pipeline and does one of two things:
 - If your paired reads have different names (e.g. a "/1" or "/2" suffix after the read name), it standardizes the names by removing the read-specific suffix. This is common with data produced on older Illumina machines. Some of the tools used by Sunbeam will fail in unexpected and inconsistent ways if read pairs don't have the same names.
 - If the names of your read pairs are the same (or you are running unpaired data), it just symlinks your reads into the sunbeam_output folder. This is usually the process that takes place, as most people aren't running data generated by old Illumina machines.

Do you mind posting the log file at this path: `/home/ubuntu/informatics/GMH/projects/.snakemake/log/2020-02-20T114303.321764.snakemake.log` so that we can take a look at what might have gone wrong? I don't see any errors in the rule output, so maybe that log file will be useful.

Do you mind also including:
 - your `sunbeam_config.yml` file
 - a brief description of how your reads were generated--e.g. what platform was used/are they simulated, or legacy data?

Thank you!

**Comment by telatin** [comment] 2020-02-20 14:15
Thanks for the prompt reply!
I don't have access to the machine used at the moment but I'll be glad to do so. The lines I posted are actually from the log mentioned, but I will share the whole file, thanks!

**Comment by telatin** [comment] 2020-02-20 16:23
So, for another attempt:
- samples.csv: https://pastebin.com/3rhijE0u
- config: https://pastebin.com/3gMj40Z6
- log:  https://pastebin.com/pTx6facm

**Comment by louiejtaylor** [comment] 2020-02-20 17:37
Hmm. The log and samples.csv files look fine (or at least unassuming). It appears as though we may have a versioning issue that we need to fix. Could you update your sunbeam_config.yml file to include a `seq_id_ending` parameter in the `qc` section, like so:

    ...
    
    qc:
      suffix: qc
      seq_id_ending: '' #add this
      # Trimmomatic
    
    ...

This basically tells the pipeline to only symlink during the `sample_intake` step, as the `seq_id_ending` is an empty string. I'm not sure what it's trying to do now (I would expect an error, but it doesn't seem like you're seeing one). Hopefully it'll work in the pipeline on re-run.

This feature is something we added later (in version 3.0 IIRC), but the `seq_id_ending` parameter should be in the config file by default in versions where the `sample_intake` rule is a part of the pipeline. I want to make sure we haven't mucked up the versioning somehow.

Also, two questions either way--how recently did you install sunbeam? and did you install from the dev or the stable branch? Thank you!

**Comment by ressy** [comment] 2020-02-20 18:33
Thanks Louis.  Those look good to me too and I think we should be OK for the configuration handling for that new option-- the way that's implemented in the latest stable version it should just default to None (or equivalently an empty string like you mentioned) for seq_id_ending, and fall back on the default symlink_to behavior ([handled here](https://github.com/sunbeam-labs/sunbeam/blob/stable/rules/qc/qc.rules#L22)).  And yeah we switched it over from a runtime default to one built into the default config for 3.0, based on what's in dev now.

I would have thought if something in that part failed you'd see a Python exception, though, like you said.  It's very strange that it just stops like that.  Since it tried to run that rule, it already thinks the input exists, so that's not the issue, and assuming what I said above is valid it shouldn't have tried to actually do anything with the file contents, so the reads themselves shouldn't be either.  But after those things I'm not sure what that leaves.  (We even have an alternate test for the old-style Illumina IDs in the test suite so both possibilities are covered!)  I'll try to help take a look at this too.

**Comment by louiejtaylor** [comment] 2020-02-20 20:10
Ah okay @ressy, I realize that I was looking at the dev branch where it looks like an error would be thrown in the [params](https://github.com/sunbeam-labs/sunbeam/blob/dev/rules/qc/qc.rules#L20) bit, but you handle that smoothly in stable with Cfg.get() (which I assume returns None if the key doesn't exist).

I really have no idea what's going on here--you'd think that there would be an exception, or that it would yell about the file not being created if there was an issue with symlinking.

@telatin--are you running this on a cluster, or another system that might redirect stdout/stderr to a non-obvious place?

**Comment by ressy** [comment] 2020-02-20 20:37
That's right!  The get method on a dictionary returns None by default, that evaluates to False, and then it  goes to the symlink part (well, in theory).

I was was wondering about the possibility of a cluster-related complication too.  It's super weird that we don't see an error but we do see the snakemake cleanup bit at the end (so it's not just truncating stdout/stderr or something).  I also tested things out by intentionally throwing an exception in the run block there, and in that case it *does* say that an error occurred in the rule when it quits.  But in the log here, it just sort of stops in its tracks.  I'll mull this over and try to come up with a way to narrow it down some more.

**Comment by telatin** [comment] 2020-02-21 09:36
So, I'm using "sunbeam v2.1.0", I added the ` seq_id_ending: '' ` to the YAML file but the problem still persists.

YAML file: https://pastebin.com/Cri1uPX3
Log file: https://pastebin.com/ZUu4Qk0k

I'm not familiar with Snakemake so I tried to have some verbose feedback altering the rule:
```
rule sample_intake:
    input:
        lambda wildcards: Samples[wildcards.sample][wildcards.rp]
    output:
        str(QC_FP/'00_samples'/'{sample}_{rp}.fastq.gz')
    params:
        suffix = Cfg['qc'].get('seq_id_ending')
    run:
        if params.suffix:
            print("[suffix=YES] input={},output={},suffix={}".format(input[0], output[0], params.suffix))
            qc.strip_seq_id_suffix(input[0], output[0], params.suffix)
        else:
            print("[suffix=NO] input={},output={}".format(input[0], output[0]))
            try:
                Path(output[0]).symlink_to(input[0])
            except Exception as e:
                print("Unable to create a symlink:\t{}".format(e))
```

So I can confirm that is the second branch of the condition  that is executed:
```
[suffix=NO] input=/.../sn_salmonella/reads/SN24_R2.fq.gz,output=/.../sn_salmonella/sunbeam/sunbeam_output/qc/00_samples/SN24_2.fastq.gz
Unable to symlink: [Errno 95] Operation not supported
```

Apparently I have an issue with the filesystem! :(
Problem solved, but it could be worth using the `try` statement for the few that could have the same issue 😅

**Comment by ressy** [comment] 2020-02-21 14:26
Aha that's it!  Thanks for trying that out.  (I had thought everything displayed went to the log, too, but it looks like the lines that say where the error occurred don't actually get logged.)  Out of curiosity what filesystem is your /home?  It's surprising to me that it's Ubuntu but with a filesystem that won't do symlinks.  I also just realized that the tests run out of a temporary directory so that's probably why they managed to run OK (assuming /tmp is ext4 or something).

@louiejtaylor I think telatin is right and there should be a bit of exception-handling there to head off any future confusion (maybe just with a `raise` statement at the end to send it farther up to Snakemake too).  I feel some responsibility here for being the one to have added this rule that's now causing trouble ;)

In the larger scheme of things it could make sense to have a chunk of information logged at the very beginning with info like operating system, filesystem, etc. since we've seen cluster/disk/network-specific weirdness from time to time.  But I'm probably getting farther out of the realm of what I have time to help with right now so that's more just thinking out loud.

**Comment by telatin** [comment] 2020-02-21 15:43
Hello, it's a virtual server running Ubuntu, but the data was in a volume in the HPC mounted via CIFS (for authentication reasons). I'll use a /local/scratch for the analysis and I will be fine!
Thanks for looking into this

**Comment by ressy** [comment] 2020-02-21 17:27
CIFS!  Now it makes sense.  Thanks, I'm glad we could track that down.

@louiejtaylor sounds like we're all set here, but, should this stay open pending improvement in `sample_intake` or should that be  separate?  I'll defer to you on that one.

**Comment by ressy** [comment] 2021-04-01 20:45
Only took a year and a bit took take another look at this (better late than never?) but now that I look, I actually can't reproduce the behavior of it not showing the exception message.  If I raise my own Python exception in a `run:` block I do see the message show up in the Snakemake output just above the `Shutting down, this might take some time.` whereas @telatin had to add that manually to see the error message.

Maybe snakemake's behavior with that sort of thing has changed since the last version?  (I just tried this on dev with 5.6.0 versus stable's 5.5.0.)  Or is there something particularly weird about this exact problem?  I don't have a Linux install that also has a filesystem that doesn't support symlinks to test that further.

**Comment by ressy** [comment] 2021-04-01 20:58
It's the former.  Snakemake 5.5.0 doesn't show exceptions raised inside rules, whereas 5.6.0 does.

With this Snakefile:

```
rule fail:
    run:
        raise Exception("blarg!")
```

I see this with Snakemake 5.5.0:

```
Error in rule fail:
    jobid: 0

Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data/home/jesse/.snakemake/log/2021-04-01T165607.377956.snakemake.log
```

and this with Snakemake 5.6.0:

```
Error in rule fail:
    jobid: 0

RuleException:
Exception in line 3 of /data/home/jesse/Snakefile:
blarg!
  File "/data/home/jesse/Snakefile", line 3, in __rule_fail
  File "/home/jesse/miniconda3/envs/sunbeam-550/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data/home/jesse/.snakemake/log/2021-04-01T165400.656725.snakemake.log
```

...all of which is one more reason to get the dev branch released as a proper stable version sooner rather than later.  But as far as this issue is concerned it should already be settled as the dev version should properly show the error message if this comes up again.

**Closed by ressy** 2021-04-01 20:58 UTC
