### ISSUE TITLE
Megahit outputs blank final.contigs.fa

### ISSUE THREAD

**Issue by aimirza** [sunbeam-labs/sunbeam#271] opened 2020-02-15 01:41 UTC
Megahit created a blank `final.contigs.fa` file on my smallest sample (2 million reads). `final.contigs.fa.300fa` file is missing. I don't have issues with other samples. The job ran with no apparent problems it seems. The log says "Merging to output final contigs." All the intermediate_contigs are there. Here is the assembly log file. Any ideas? 

[log.txt](https://github.com/sunbeam-labs/sunbeam/files/4207608/log.txt)

**Comment by aimirza** [comment] 2020-02-19 20:08
For some reason, it doesn't want to merge the intermediate contigs. I reran assembly with `--rerun-incomplete` parameter after deleting the empty` final.contigs.fa` file from the `sunbeam_output/assembly/megahit/{sample}_asm` directory hoping it would merge them. Didn't work, it just ran paired megahit again and still outputted a blank final.contigs.fa. Finally, after deleting the whole `sunbeam_output/assembly/megahit/{sample}_asm` directory it worked. Not sure why this issue happens. Maybe change sunbeam to not rerun megahit if the intermediate files are present and have a merging step.

**Comment by louiejtaylor** [comment] 2020-02-20 13:40
Thanks for the issue, and sorry for the slow response! 

Hmm. It sounds like something failed in MEGAHIT during the initial running of the rule, in a way that impeded subsequent attempts to build contigs for that sample. As far as I can tell from the log file, it looks like MEGAHIT thought it ran fine--which is extra confusing.

As far as fixing the problem, you did exactly what I would've suggested--deleting the intermediate directory and rerunning the sample. Maybe we can explicitly state this in the rule, although I'm not sure it'll help, since it sounds like the rule ran fine (but just created an empty contigs file). Do you mind sharing the version of MEGAHIT you're running so I can try to reproduce this and hopefully avoid people having this problem in the future?

**Comment by aimirza** [comment] 2020-02-21 00:05
I used MEGAHIT v1.1.3

I couldn't find a similar issue in the megahit github repository. I wonder if to rerun Megahit the intermediate files must be deleted first for megahit to properly run.

**Comment by evolphotonics** [comment] 2022-08-17 06:48
@louiejtaylor, I am facing the same issue with Megahit v1.2.9. any help much appreciated
attaching the logs...
[megahit_run_log.txt](https://github.com/sunbeam-labs/sunbeam/files/9357098/megahit_run_log.txt)
[megahit.nohup.output.txt](https://github.com/sunbeam-labs/sunbeam/files/9357100/megahit.nohup.output.txt)
[options.json.txt](https://github.com/sunbeam-labs/sunbeam/files/9357106/options.json.txt)

**Comment by Ulthran** [comment] 2022-09-29 14:21
@evolphotonics I notice `force_overwrite` is false, I wonder if setting that to true would achieve the desired effect of automatically overwriting intermediate files. Unfortunately I'm not sure there's anything to be done about it failing silently sometimes, but `force_overwrite` might make it easier to rerun in those cases.

**Comment by evolphotonics** [comment] 2022-09-29 15:57
thanks - I got it to work in the end...it did not happen when I ran it
again or when I changed some parameters, but good to know about
*force_overwrite*

**Comment by Ulthran** [comment] 2022-09-29 17:39
Great, thanks for the reply. I'm going to close this issue, please open a new one if this kind of behavior is observed in sunbeam3.

**Closed by Ulthran** 2022-09-29 17:39 UTC
