### ISSUE TITLE
"No such file or directory" after sunbeam init

### ISSUE THREAD

**Issue by gputzel** [sunbeam-labs/sunbeam#157] opened 2018-07-03 19:39 UTC
Following the docs I tried

`sunbeam init my_project --data_fp FASTQ`

where `FASTQ` is a directory containing several `gzipped` `FASTQ` files. I get:

    Traceback (most recent call last):
      File "/home/myusername/miniconda3/envs/sunbeam/bin/sunbeam", line 11, in <module>
        sys.exit(main())
      File "/home/myusername/miniconda3/envs/sunbeam/lib/python3.5/site-packages/sunbeamlib/scripts/command.py", line 40, in main
        Init(remaining)
      File "/home/myusername/miniconda3/envs/sunbeam/lib/python3.5/site-packages/sunbeamlib/scripts/init.py", line 60, in main
        project_fp = args.project_fp.resolve()
      File "/home/myusername/miniconda3/envs/sunbeam/lib/python3.5/pathlib.py", line 1109, in resolve
        s = self._flavour.resolve(self)
      File "/home/myusername/miniconda3/envs/sunbeam/lib/python3.5/pathlib.py", line 330, in resolve
        return _resolve(base, str(path)) or sep
      File "/home/myusername/miniconda3/envs/sunbeam/lib/python3.5/pathlib.py", line 315, in _resolve
        target = accessor.readlink(newpath)
      File "/home/myusername/miniconda3/envs/sunbeam/lib/python3.5/pathlib.py", line 422, in readlink
        return os.readlink(path)
    FileNotFoundError: [Errno 2] No such file or directory: '/scratch001/myusername/try_sunbeam/my_project'

**Comment by eclarke** [comment] 2018-07-03 21:03
Maybe a dumb question, but does that directory actually exist on your machine?

**Comment by gputzel** [comment] 2018-07-03 21:22
No indeed :-)
I expected it would be created by that command. My bad.

**Comment by eclarke** [comment] 2018-07-03 21:43
Oh I see now. You’re correct- it actually should have been created. Can you normally create folders in the parent directory?

**Comment by gputzel** [comment] 2018-07-05 13:06
Yes, I'm working in a directory where I have permission to create directories.

**Comment by louiejtaylor** [comment] 2018-07-10 18:23
Probably another few dumb questions incoming as I try to reproduce the problem you're having. 

1. What OS/version are you running? What version of conda (`conda -V`)?
2. Where is your sunbeam directory located? Is it in /scratch001/myusername/try_sunbeam?
3. Is there any particular reason you're working in /scratch001/ rather than your home dir?

**Comment by louiejtaylor** [comment] 2018-07-10 18:44
Reproduced the issue. For some reason Sunbeam isn't creating the directory, although I know it did up until very recently. Pinging @eclarke to see if he knows whether something changed recently, but I can dig through the source to see what might be to blame.

As a kind of lame workaround, you can just `mkdir my_project` and it should work (a Sunbeam run worked for me just now at least--if you see a trimmomatic error please see my [comment](https://github.com/sunbeam-labs/sunbeam/issues/150#issuecomment-403925892) on #150).

Let me know if that works and I'll try to track down the part that broke!

**Comment by eclarke** [comment] 2018-07-10 19:03
Unexpectedly, the call to `Path.resolve()` here: https://github.com/sunbeam-labs/sunbeam/blob/177d28d371ab50764e0aac0f8a78d8ced19f91b7/sunbeamlib/scripts/init.py#L60  throws an error if that path does not exist. This appears to have changed in Python 3.6 (https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve), and we don't test 3.6 in our integration tests currently (though I'm enabling that now). I'll submit a pull request shortly.

**Comment by eclarke** [comment] 2018-07-10 19:14
Turns out we do test Python 3.6 so I'm not sure where the issue arose. @louiejtaylor since you can replicate this, can you check out the relevant branch I just made (`project_fp-create`) and see if it fixes it?

**Comment by eclarke** [comment] 2018-07-10 19:36
Okay great! Merged the branch and will close this as fixed. @gputzel, if you're still interested in trying sunbeam, we will have a new stable release pushed out by tonight that should fix the errors you've encountered. Thank you for your time filing these issues!

**Closed by eclarke** 2018-07-10 19:36 UTC
